FROM p7-hdfs

RUN apt-get update && \
    apt-get install -y wget curl openjdk-25-jdk python3 python3-pip iputils-ping iproute2

COPY src/requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt --break-system-packages

# Kafka (see https://kafka.apache.org/quickstart, KRaft config)
# faster mirror (switch to archive.apache.org if this stops working)
RUN wget https://downloads.apache.org/kafka/4.3.1/kafka_2.13-4.3.1.tgz && \
    #RUN wget https://archive.apache.org/dist/kafka/4.3.1/kafka_2.13-4.3.1.tgz && \
    tar -xf kafka_2.13-4.3.1.tgz && \
    rm kafka_2.13-4.3.1.tgz

# from bin/kafka-storage.sh random-uuid
ENV KAFKA_CLUSTER_ID=dCHffFWYTCKWXiesmJMN9w

CMD sh -c "cd /kafka_2.13-4.3.1 && \
    bin/kafka-storage.sh format --standalone -t $KAFKA_CLUSTER_ID -c config/server.properties && \
    bin/kafka-server-start.sh config/server.properties --override auto.create.topics.enable=false"